import Head from 'next/head'
import 'bootstrap/dist/css/bootstrap.min.css';
import Banner from "../components/Banner/banner.component";
// import FindBySearch from "../components/FindBySearch/findbysearch.component";
import 'react-input-range/lib/css/index.css'
import Stock from "../components/Stock/stock.component";
import FindBySearchHome from '../components/FindBySearch/FindBySearchForm/findBySearchHome.component';


export default function Home() {
  return (
    <>
    <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Banner/>
        <FindBySearchHome />
        <Stock/>
    </> 
  )
}
