import Head from 'next/head'
import 'bootstrap/dist/css/bootstrap.min.css';
import Banner from "../components/Banner/banner.component";
import FindBySearch from "../components/FindBySearch/findbysearch.component";
import 'react-input-range/lib/css/index.css'
import Stock from "../components/Stock/stock.component";
import ExportInfoSection from "../components/ExportInfoSection/exportInfoSection.component";
import PageFooter from "../components/PageFooter/PageFooter.component";
import CompanyInfoSection from "../components/CompanyInfoSection/companyInfoSection.component";

export default function Home() {
  return (
    <>
    <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Banner/>
        <FindBySearch/>
        <Stock/>
        <ExportInfoSection/>
        <CompanyInfoSection/>
        <PageFooter/>
    </> 
  )
}
